server:
  host: "0.0.0.0"
  port: 3000
  mode: "debug"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  max_header_bytes: 1048576  # 1MB
  shutdown_timeout: "10s"
  enable_cors: true
  enable_swagger: true

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres123"
  name: "teable"
  ssl_mode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"
  log_level: "info"  # 显示所有SQL查询

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  dial_timeout: "5s"

jwt:
  secret: "your-secret-key-change-in-production"
  access_token_ttl: "24h"
  refresh_token_ttl: "168h"  # 7 days
  issuer: "teable-api"
  enable_refresh: true

storage:
  type: "local"
  local:
    upload_path: "./uploads"
    url_prefix: "/uploads"
  cdn_domain: ""

logger:
  level: "info"
  format: "json"
  output_path: "stdout"

queue:
  redis_addr: "localhost:6379"
  redis_password: ""
  redis_db: 1
  max_retries: 3
  queue_critical: "critical"
  queue_default: "default"
  queue_low: "low"

websocket:
  enable_redis_pubsub: true
  redis_prefix: "teable:ws"
  heartbeat_interval: "30s"
  connection_timeout: "60s"
  max_connections: 1000
  enable_presence: true
